In [4]:
import numpy as np

In [11]:
mtx1 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

In [12]:
mtx2 = np.array([[11, 12, 13, 14],
                 [15, 16, 17, 18],
                 [19, 20, 21, 22]])

In [13]:
mtx1 + mtx2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [14]:
mtx1 - mtx2

array([[-10, -10, -10, -10],
       [-10, -10, -10, -10],
       [-10, -10, -10, -10]])

In [15]:
mtx1 * mtx2

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171, 200, 231, 264]])

In [16]:
mtx1 / mtx2

array([[0.09090909, 0.16666667, 0.23076923, 0.28571429],
       [0.33333333, 0.375     , 0.41176471, 0.44444444],
       [0.47368421, 0.5       , 0.52380952, 0.54545455]])

In [17]:
mtx3 = ([[15, 16, 17],
         [18, 19, 20]])

In [22]:
mtx1 == mtx2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [25]:
mtx1 != mtx2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [26]:
mtx1 <= mtx2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [27]:
mtx1 >= mtx2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [29]:
mtx1 > mtx2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [30]:
import pandas as pd